name: Repo Sync

on:
  push:
    branches: [main]

jobs:
  stainless:
    environment: staging
    concurrency: upload-openapi-spec-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: './openapi.json'
          config_path: './openapi.stainless.yml'
          project_name: 'gotue'